name: Quality Checks

on:
  pull_request:
  push:
    branches:
      - "main"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  server:
    name: Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

  client:
    name: Client
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/client
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup Golang
        uses: actions/setup-go@v6
        with:
          go-version-file: apps/client/go.mod
          cache-dependency-path: apps/client/go.sum

      - name: Test
        run: go test ./...

      - name: Vet
        run: go vet ./...

  web:
    name: Web
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/web
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10.34.1

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: apps/web/pnpm-lock.yaml

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Lint
        run: pnpm lint

      - name: Check Formatting
        run: pnpm fmt:check
